apiVersion: v1
kind: Service
metadata:
  name: restaurant-ui
  labels:
    app: restaurant-ui
spec:
  type: ClusterIP
  selector:
    app: restaurant-ui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9004
